### ISSUE TITLE
How to build this one... 

### ISSUE THREAD

**Issue by phuyem** [ui-router/sample-app-angularjs#36]
I have download the source code, it looks great, very clear. Then I moved it my local nginx/apache , ready for some action but it is not working. I have tried npm install and yarn install but not successful.

Finally "yarn build" is the one. 

I know this question is kinda dummy but it would be nice if we have some small guide section for building this sample

**Comment by christopherthielen** [comment]
```
yarn
yarn start
```

or if you want to build it and run your own server:

```
yarn
yarn build
```
then serve the files where `index.html` resides (i.e., `python -m SimpleHTTPServer`)
